version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - our_food_network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=docker_use
      - PUID=1000
      - PGID=1000